name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services: {}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install root deps
        run: npm ci
      - name: Install frontend deps
        run: npm run install:frontend
      - name: Build frontend
        run: npm run build:frontend
      - name: Run unit tests
        run: npm run test:unit
      - name: Start server
        run: |
          node backend/server.js &
          sleep 2
      - name: Run Postman collection (Newman)
        run: npx newman run tests/postman/collection.json
      - name: Run Selenium tests
        run: node tests/selenium/run_selenium_tests.js
